version: '3'
services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    restart: always
    ports: 
      - "3307:3306"
    environment: 
      - MYSQL_ONETIME_PASSWORD=true
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jobsearch
    volumes:
      - ./mysql-data:/var/lib/mysql:rw
      - ./mysql-init:/docker-entrypoint-initdb.d/:ro
        
  worksearch-app:
    container_name: worksearch-app
    image: percivalbragg/worksearch
    restart: on-failure
    ports: 
      - "8080:8080"
    depends_on: 
      - "mysql-db"  
    environment:      
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root  
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/jobsearch?useSSL=false&allowPublicKeyRetrieval=true
      